### ISSUE TITLE
All the requirements are satisfied, but it is still not resolved

### ISSUE THREAD

**Issue by EatSleepCSRepeat** [NeKitDSS/gd.py#206]
![image](https://github.com/nekitdev/gd.py/assets/163324856/685d2bae-ca1b-4c99-8359-05c7931acb81)

**Comment by johnslavik** [comment]
If all the requirements are satisfied, this is not a problem with gd.py—most likely your Pylance (judging by the screen) operates in a misconfigured virtual enviroment.

Try reconfiguring your environment in the right bottom corner of VSCode and maybe Ctrl + Shift + P > Clear Cache and Reload Window.

Again, this is not an issue with gd.py.
